- name: openconfig-route-programming
  docs:
    - yang/route-programming/openconfig-route-programming-state.yang
  build:
    - yang/route-programming/openconfig-route-programming-state.yang
  run-ci: true
